export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';
export const CART_EMPTY_ITEM = 'CART_EMPTY_ITEM';

export const CART_SAVE_SHPPING_ADDRESS = 'CART_SAVE_SHPPING_ADDRESS';

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';