const USER_CONTANTS = {
    USER_SIGNING_REQUEST : 'USER_SIGNING_REQUEST',
    USER_SIGNING_SUCCESS : 'USER_SIGNING_SUCCESS',
    USER_SIGNING_FAIL : 'USER_SIGNING_FAIL',

    USER_SIGNOUT : 'USER_SIGNOUT',
    
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL : 'USER_REGISTER_FAIL',

    USER_DETAILS_REQUEST : 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS : 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL : 'USER_DETAILS_FAIL',

    USER_UPDATE_PROFILE_REQUEST : 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS : 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL : 'USER_UPDATE_PROFILE_FAIL',
}

export default USER_CONTANTS;